import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/app/providers/auth";
import { Header } from "@/app/components/ui/header";
import { Toaster } from "./components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shortener",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} flex min-h-screen w-full flex-col items-center antialiased`}
      >
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
